name: Blog website builder

on:
  workflow_dispatch:
  push:
    branches:
      - staging
      - live
    paths:
      - content/**
      - themes/**
      - config.toml

jobs:
  build-and-deploy:
    name: Build & deploy site to GitHub Pages.
    env:
      IS_STAGING: ${{ github.repository == 'shymega/blog-staging.shymega.org.uk'}}
      IS_PROD:  ${{ github.repository == 'shymega/blog-live.shymega.org.uk' }}
    permissions:
      actions: read
      contents: write
      pages: write
    concurrency: blog-build-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build blog
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ext-alpine
        env: production
        command: -b ${{ env.IS_STAGING == true && 'https://blog-staging.shymega.org.uk' || env.IS_PROD == true && 'https://blog.shymega.org.uk' }}
    - name: Create supporting file (.nojekyll)
      run: sudo touch ./public/.nojekyll
    - name: Deploy to GitHub
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        single-commit: true
